spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yupao?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 86400
    store-type: redis
server:
  port: 8080
  servlet:
    context-path: "/api"
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.guidian.searchFriends.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn